version: "3.9"  
services:
  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
  notes.api:
    image: ${DOCKER_REGISTRY-}notesappapi
    build:
      context: .
      dockerfile: NotesApp.Api/Dockerfile
    ports:
      - "7001:80"
